// Copies the virtual pad library (sdk/pad/virtual-pad.js, the one source) into its two places:
//   js/core/virtual-pad.js        the shell draws the touch pad with it
//   sdk/mypc-sdk.js               between "/* vpad:begin */" and "/* vpad:end */" (MyPC.pad), as a private variable
// Run after editing sdk/pad/virtual-pad.js:  node tools/sync-pad.mjs   (tests fail when the copies differ)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = fs.readFileSync(path.join(ROOT, 'sdk/pad/virtual-pad.js'), 'utf8').replace(/\s+$/, '') + '\n';
fs.writeFileSync(path.join(ROOT, 'js/core/virtual-pad.js'), src);

const sdkPath = path.join(ROOT, 'sdk/mypc-sdk.js');
let sdk = fs.readFileSync(sdkPath, 'utf8');
const a = sdk.indexOf('    /* vpad:begin'), b = sdk.indexOf('/* vpad:end */');
if (a < 0 || b < 0) throw new Error('vpad markers not found in sdk/mypc-sdk.js');
const block = src.replace('window.VirtualPad = (function', 'var VirtualPad = (function').replace(/\s+$/, '').split('\n').map((l) => (l ? '    ' + l : l)).join('\n');
sdk = sdk.slice(0, a) + '    /* vpad:begin (generated by tools/sync-pad.mjs from sdk/pad/virtual-pad.js: do not edit here) */\n' + block + '\n    ' + sdk.slice(b);
fs.writeFileSync(sdkPath, sdk);
console.log('synced js/core/virtual-pad.js and the block in sdk/mypc-sdk.js');
